# Aquisição de dados

In [ ]:
import pandas as pd

In [ ]:
vendas = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/vendas_ficticias.csv")
df = pd.DataFrame(vendas)
df

,ID,Produto,Categoria,Preço,Quantidade,Data_Venda,Vendedor
0,1,Produto C,Categoria 3,'27.82',19,2023-01-01,Vendedor 1
1,2,Produto A,Categoria 1,49.42,14,2023-01-02,Vendedor 3
2,3,Produto C,Categoria 3,46.79,13,2023-01-03,Vendedor 2
3,4,Produto C,Categoria 1,48.6,15,2023-01-04,Vendedor 3
4,5,Produto A,Categoria 3,62.7,16,2023-01-05,Vendedor 1
...,...,...,...,...,...,...,...
4995,4996,Produto A,Categoria 3,44.46,15,2036-09-04,Vendedor 2
4996,4997,Produto B,Categoria 1,57.38,9,2036-09-05,Vendedor 3
4997,4998,Produto C,Categoria 2,71.05,7,2036-09-06,Vendedor 1
4998,4999,Produto B,Categoria 2,35.76,16,2036-09-07,Vendedor 2
4999,5000,Produto A,Categoria 3,32.69,3,2036-09-08,Vendedor 3

# Análise Exploratória

In [ ]:
#Verificar Tipos
df.dtypes

ID             int64
Produto       object
Categoria     object
Preço         object
Quantidade     int64
Data_Venda    object
Vendedor      object
dtype: object

In [ ]:
# Verificar duplicidade
print(f"""Produtos duplicados: {df.Produto.duplicated().sum()}
Categorias duplicadas: {df.Categoria.duplicated().sum()}
Preço duplicados: {df.Preço.duplicated().sum()}
Data_Venda duplicados: {df.Data_Venda.duplicated().sum()}
Vendedor duplicados: {df.Vendedor.duplicated().sum()}""")

Produtos duplicados: 4996
Categorias duplicadas: 4996
Preço duplicados: 1158
Data_Venda duplicados: 0
Vendedor duplicados: 4996

In [ ]:
# Verificar se há dados em falta
df.isna().sum()

ID             0
Produto        3
Categoria      1
Preço          0
Quantidade     0
Data_Venda     1
Vendedor      11
dtype: int64

## Resultado da análise:
1. A coluna "Preço" está sendo preenchida com o tipo "object"
####solução: converter o tipo "object" para "float64"
2. A coluna "Data_Venda" está sendo preenchida com o tipo "object"
####solução: converter o tipo "object" para "datetime"
3. A coluna "Produto" possui 3 valores nulos
4. A coluna "Categoria" possui 1 valor nulo
5. A coluna "Data_Venda" possui 1 valor nulo
6. A coluna "Vendedor" possui 11 valores nulos
####opções de resolução:
- Adicionar as informações ausentes no arquivo base
- Atribuir um valor fixo para os dados faltantes
- Atribuir o valor da média respectiva a cada dado, para cada informação ausente
- Atribuir o valor da mediana respectiva a cada dado, para cada informação
- Atribuir o valor da moda respectiva a cada dado, para cada informação
- Atribuir o valor máximo ou mínimo respectivo a cada dado
- Em último caso, deletar a linha ou coluna em que há ausencia de dados

# Data Prep

In [ ]:
#convertendo os tipos
df.Preço = df.Preço.replace("'", "", regex=True)

df = df.astype(
    {
        'Preço': "float"
    }
)

df.Data_Venda = pd.to_datetime(df.Data_Venda, format = "%Y-%m-%d")